
    create sequence activity_schedules_SEQ start with 1 increment by 50;

    create sequence activity_SEQ start with 1 increment by 50;

    create sequence bookings_SEQ start with 1 increment by 50;

    create sequence client_package_credits_SEQ start with 1 increment by 50;

    create sequence client_packages_SEQ start with 1 increment by 50;

    create sequence headquarters_SEQ start with 1 increment by 50;

    create sequence organizations_SEQ start with 1 increment by 50;

    create sequence payments_SEQ start with 1 increment by 50;

    create sequence session_instances_SEQ start with 1 increment by 50;

    create sequence users_SEQ start with 1 increment by 50;

    create table activity (
        isActive boolean not null,
        createdAt timestamp(6),
        deletedAt timestamp(6),
        deleted_at timestamp(6) with time zone,
        hq_id bigint not null,
        id bigint not null,
        updatedAt timestamp(6),
        description varchar(1000),
        name varchar(255) not null,
        primary key (id)
    );

    comment on column activity.deleted_at is
        'Soft-delete indicator';

    create table activity_schedules (
        active_from date,
        active_until date,
        day_of_week integer not null,
        duration_minutes integer not null,
        is_active boolean not null,
        scheduled_date date,
        start_time time(0) not null,
        activity_id bigint not null,
        headquarters_id bigint not null,
        id bigint not null,
        organization_id bigint not null,
        template_type varchar(255) not null check ((template_type in ('WEEKLY_RANGE','ONE_TIME','ONE_TIME_DISPOSABLE'))),
        primary key (id)
    );

    create table bookings (
        cancelled_at timestamp(6) with time zone,
        consumed_package_id bigint,
        created_at timestamp(6) with time zone,
        id bigint not null,
        promoted_booking_id bigint,
        session_id bigint not null,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        cancel_request_id varchar(128),
        create_request_id varchar(128),
        status varchar(255) not null check ((status in ('CONFIRMED','WAITLISTED','CANCELLED','ATTENDED','NO_SHOW'))),
        primary key (id),
        constraint uq_bookings_create_request_id unique (create_request_id),
        constraint uq_bookings_cancel_request_id unique (cancel_request_id)
    );

    create table client_package_credits (
        tokens integer not null,
        activity_id bigint not null,
        id bigint not null,
        package_id bigint not null,
        primary key (id),
        constraint uq_client_package_activity unique (package_id, activity_id)
    );

    create table client_packages (
        active boolean not null,
        period_end date not null,
        period_start date not null,
        created_at timestamp(6) with time zone,
        id bigint not null,
        payment_id bigint,
        updated_at timestamp(6) with time zone,
        user_id bigint not null,
        primary key (id)
    );

    create table headquarters (
        id bigint not null,
        organization_id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table organizations (
        id bigint not null,
        name varchar(255) not null,
        primary key (id)
    );

    create table payments (
        amount numeric(12,2) not null,
        paid_at date not null,
        created_at timestamp(6) with time zone,
        id bigint not null,
        updated_at timestamp(6) with time zone,
        method varchar(24) not null check ((method in ('CASH','CARD','TRANSFER','OTHER'))),
        primary key (id)
    );

    create table refresh_tokens (
        revoked boolean not null,
        createdAt timestamp(6) with time zone not null,
        expiresAt timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        revokedAt timestamp(6) with time zone,
        userId bigint not null,
        ipAddress varchar(45),
        deviceInfo varchar(500),
        token varchar(512) not null unique,
        firebaseUid varchar(255) not null,
        primary key (id)
    );

    create table session_instances (
        cancellation_allow_late_cancel boolean,
        cancellation_min_hours_before_start integer,
        max_participants integer,
        waitlist_enabled boolean,
        waitlist_max_size integer,
        activity_id bigint not null,
        created_at timestamp(6) with time zone,
        ends_at timestamp(6) with time zone not null,
        headquarters_id bigint not null,
        id bigint not null,
        organization_id bigint not null,
        starts_at timestamp(6) with time zone not null,
        updated_at timestamp(6) with time zone,
        source varchar(255) not null check ((source in ('MANUAL','SCHEDULER'))),
        status varchar(255) not null check ((status in ('OPEN','CLOSED','CANCELLED'))),
        waitlist_strategy varchar(255) check ((waitlist_strategy in ('FIFO'))),
        primary key (id),
        constraint uq_session_instances_slot unique (organization_id, headquarters_id, activity_id, starts_at)
    );

    create table user_roles (
        user_id bigint not null,
        role varchar(255) check ((role in ('CLIENT','PROFESSOR','ORG_ADMIN','ORG_OWNER','SUPERADMIN')))
    );

    create table users (
        active boolean not null,
        id bigint not null,
        email varchar(255) not null unique,
        firebase_uid varchar(255) not null unique,
        last_name varchar(255) not null,
        name varchar(255) not null,
        primary key (id)
    );

    create index idx_activity_schedules_hq_day 
       on activity_schedules (headquarters_id, day_of_week);

    create index idx_activity_schedules_activity_day 
       on activity_schedules (activity_id, day_of_week);

    create index idx_bookings_session_status 
       on bookings (session_id, status);

    create index idx_bookings_user_status 
       on bookings (user_id, status);

    create index idx_bookings_created_at 
       on bookings (created_at);

    create index idx_client_package_credits_package 
       on client_package_credits (package_id);

    create index idx_client_package_credits_activity 
       on client_package_credits (activity_id);

    create index idx_client_packages_user_active 
       on client_packages (user_id, active);

    create index idx_client_packages_period_end 
       on client_packages (period_end);

    create index idx_payments_paid_at 
       on payments (paid_at);

    create index idx_payments_method 
       on payments (method);

    create index idx_refresh_token_firebase_uid 
       on refresh_tokens (firebaseUid);

    create index idx_refresh_token_user_id 
       on refresh_tokens (userId);

    create index idx_session_instances_hq_starts_at 
       on session_instances (headquarters_id, starts_at);

    create index idx_session_instances_activity_starts_at 
       on session_instances (activity_id, starts_at);

    create index idx_session_instances_status_starts_at 
       on session_instances (status, starts_at);

    alter table if exists activity 
       add constraint FKh5qajputrmmneuesbit34v88h 
       foreign key (hq_id) 
       references headquarters;

    alter table if exists client_package_credits 
       add constraint FK2yiyc9ssh9r5xrk10lpg8m4g7 
       foreign key (package_id) 
       references client_packages;

    alter table if exists headquarters 
       add constraint FKd6d07vdg6dwrbns70v521u1ee 
       foreign key (organization_id) 
       references organizations;

    alter table if exists user_roles 
       add constraint FKhfh9dx7w3ubf1co1vdev94g3f 
       foreign key (user_id) 
       references users;
